# Use node 21.5 as the base image
FROM node:21.5

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Accept IMAGE_TAG as a build argument
ARG IMAGE_TAG

# Use the build argument to set an environment variable (if needed inside the application)
ENV NEXT_PUBLIC_IMAGE_TAG=$IMAGE_TAG

# Build the application
RUN npm run build

ENV PORT=80

# Set the command to run the application
CMD npm run start

# Expose port 80
EXPOSE 80
