# Use node 21.5 as the base image
FROM node:21.5

# Set the working directory inside the container
WORKDIR /app

# Copy the application files to the container
COPY /hello-world .

# Install dependencies
RUN npm install

# Accept IMAGE_TAG as a build argument
ARG IMAGE_TAG

# Use the build argument to set an environment variable (if needed inside the application)
ENV NEXT_PUBLIC_IMAGE_TAG=$IMAGE_TAG

# Build the application
RUN npm run build

# Set the command to run the application
CMD npm run start

# Expose port 3000
EXPOSE 3000
